<div style="text-align: center">
<img src="https://github.com/LinkedEarth/Logos/blob/master/PyleoTUPS/pyleotups_logo.png?raw=true" alt="PyleoTUPS logo" width="400">
</div>

# Querying the NOAA NCEI Database

## Authors

Deborah Khider [![ORCID](https://img.shields.io/badge/ORCID-0000--0001--7501--8430-A6CE39?logo=orcid)](https://orcid.org/0000-0001-7501-8430), Dhiren Oswal [![ORCID](https://img.shields.io/badge/ORCID-0009--0001--2495--2626-A6CE39?logo=orcid)](https://orcid.org/0009-0001-2495-2626)


## Preamble

In a [previous chapter](02_b_PANGAEAObject.ipynb), you learned how to create a [`PangaeaDataset` object](https://pyleotups.readthedocs.io/en/latest/api.html#pyleotups.core.PangaeaDataset.PangaeaDataset) and its many functionalities. We won't be revisiting those here; just know that regardless of how many datasets are returned, the functions will apply. 

This tutorial demonstrates how to query the PANGAEA database. A list of search parameters available in `PyleoTUPS` can be found here. Note that many PANGAEA search terms have been mapped to their NOAA NCEI equivalents for consistency.

* `study_ids` (int, str, or list, optional) – One or more PANGAEA dataset identifiers (numeric ID or DOI string). If provided, performs direct lookup and ignores other filters.

* `topic` (str, optional) – Filter datasets by PANGAEA topic classification. Must be one of the predefined topics: - “all” (default) - “Agriculture” - “Atmosphere” - “Biological Classification” - “Biosphere” - “Chemistry” - “Cryosphere” - “Ecology” - “Fisheries” - “Geophysics” - “Human Dimensions” - “Lakes & Rivers” - “Land Surface” - “Lithosphere” - “Oceans” - “Paleontology” If set to “all” or omitted, no topic filtering is applied.

* `search_text` (str, optional) – Free-text search query applied across dataset metadata. Maps to PANGAEA full-text search parameter ‘q’. Example: ‘stable carbon and oxygen isotopes’.

* `investigators` (str or list[str], optional) – Author names. Mapped internally to PANGAEA query syntax: author:<name>

* `variable_name` (str or list[str], optional) – Name of parameters/variables (columns) present in dataset tables. Internally mapped to PANGAEA query term: parameter:<variable_name>

* `min_lat` (float, optional) – Latitude bounds (–90..90).

* `max_lat` (float, optional) – Latitude bounds (–90..90).

* `min_lon` (float, optional) – Longitude bounds (–180..180)

* `max_lon` (float, optional) – Longitude bounds (–180..180)

* `limit` (int, default 100, maximum 500) – Maximum number of results returned.

* `skip` (int, default 0) – Number of results to skip (pagination). Maps to PANGAEA ‘offset’

<div style="border-left: 4px solid #1f77b4; background: #f0f8ff; padding: 0.5em 1em; border-radius: 4px;">
  <strong>Note:</strong> Notice that time parameters are not part of the possible search terms. This is because PANGAEA does not store this information as part of its metadata. `AGE` is treated as a variable and is only accessible through the date tables. For a full description of the problem and the solutions we have considered, see this <a href='https://github.com/LinkedEarth/PyleoTUPS/issues/35'>GitHub issue</a>.

  Another major difference between how PANGAEA handles queries compared to NOAA NCEI is that PANGAEA queries are text-based. When you fill out the parameters above, `PyleoTUPS` construct the string search query for you. Concretely, however, text-based searches are less structures and therefore less reproducible than parameter searches. Results may vary based on metadata completeness. 
</div>

A list of available search term is available [here](https://wiki.pangaea.de/wiki/PANGAEA_search).

### Goals

- Perform query on PANGAEA database using search parameters.
- Extend query using the `search_text` parameter and PANGAEA's [fields](https://wiki.pangaea.de/wiki/PANGAEA_search)
- Dealing with Collections 

### Prerequisite

- Understanding of PANGAEA datasets and associated search API
- [PyleoTUPS `PANGAEADataset` object](02_b_PANGAEAObject.ipynb)

### Reading time

15 min

Let's import our packages!

In [1]:
import pyleotups as pt
import pandas as pd

## Study Query

In the notebook introducing the [`PangaeaDataset` object](02_b_PANGAEAObject.ipynb), we introduced the concept of searching by `study_ids`. If you are familiar with the [`pangaeapy` package](https://pypi.org/project/pangaeapy/), this is one of the easiest way to get data from the database.

These IDs correspond to the last six digits of the DOI PANGAEA mints for each of this dataset. Let's use the study by [van der Bilt et al. (2016)](https://doi.org/10.1016/j.quascirev.2016.10.006), whose data are available [here](https://doi.org/10.1594/PANGAEA.868935). The DOI is `10.1594/PANGAEA.868935`, resuting in the following search:

In [4]:
ds = pt.PangaeaDataset()
res = ds.search_studies(study_ids = '868935')
display(res)

[2026-04-30 09:14:09,644][INFO] - Registering Study 868935 via direct lookup.
[2026-04-30 09:14:11,278][INFO] - Retrived 1 studies

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,868935,Holocene-length alkenone-based summer temperat...,12353,1144,-10403,806,None,[],"van der Bilt, Willem G M, D'Andrea, William J,...","van der Bilt, Willem G M; D'Andrea, William J;...",[AMP112],[],None

You may have noticed that the parameter name is in a plural form. Yes, this means that you can query data from multiple datasets at the same time.

Let's get the [second dataset](https://doi.org/10.1594/PANGAEA.868936) in the collection corresponding to the [van der Bilt et al. (2016)](https://doi.org/10.1016/j.quascirev.2016.10.006) study.

In [5]:
ds = pt.PangaeaDataset()
res = ds.search_studies(study_ids = ['868935','868936'])
display(res)

[2026-04-30 09:18:21,005][INFO] - Registering Study 868935 via direct lookup.
[2026-04-30 09:18:22,625][INFO] - Registering Study 868936 via direct lookup.
[2026-04-30 09:18:24,265][INFO] - Retrived 2 studies

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,868935,Holocene-length alkenone-based summer temperat...,12353,1144,-10403,806,None,[],"van der Bilt, Willem G M, D'Andrea, William J,...","van der Bilt, Willem G M; D'Andrea, William J;...",[AMP112],[],None
1,868936,Holocene-length alkenone-based summer temperat...,11117,533,-9167,1417,None,[],"van der Bilt, Willem G M, D'Andrea, William J,...","van der Bilt, Willem G M; D'Andrea, William J;...",[HAP0212],[],None

## Investigator query

Let's search for datasets with a specific investigator.

In [10]:
ds = pt.PangaeaDataset()
res = ds.search_studies(investigators = "Khider, D.")
display(res.head())

[2026-04-30 10:33:38,765][INFO] - Limit set to 100

{'q': 'author:Khider, D.', 'bbox': None, 'limit': 100, 'offset': 0}

[2026-04-30 10:34:28,995][INFO] - Retrived 31 studies
[2026-04-30 10:34:29,000][WARNING] - The search contains dataset(s) [830589, 897517, 921315, 965845] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,830589,Stable isotope record of sediment core MD98-2177,NaN,NaN,NaN,NaN,We present a reconstruction of El Niño Souther...,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],"[830586, 830587, 830588]"
1,897517,Globigerinoides ruber sediment trap data in th...,NaN,NaN,NaN,NaN,We present results here from a high-resolution...,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[],[],"[897509, 897512, 897513, 897514, 897515, 897516]"
2,830588,(Table 3) Lead 214 and Lead 210 concentration ...,NaN,NaN,NaN,NaN,NaN,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
3,897512,Globigerinoides ruber flux analysis from a lon...,NaN,NaN,NaN,NaN,NaN,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
4,830586,(Table S1) Stable carbon and oxygen isotope ra...,1231.0,103.0,704.0,1851.0,NaN,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None

The query returned 31 datasets. Note that PyleoTUPS warns us that some of these are collections. As discussed in the [`PangaeaObject` tutorial](02_b_PANGAEAObject.ipynb), collections group datasets that belong to the same study. Collections are necessary in PANGAEA because each data table is its own dataset with a unique DOI. Consider a study in which two sediment cores are analyzed for Mg/Ca and $\delta^{18}$O. he data for both cores might appear in the same table under different `Event` labels, but if the data differ substantially, they may be reported in separate tables, and therefore separate datasets.

This is one of the key differences between the two repositories. NOAA NCEI groups data by study, allowing a one-to-many relationship between a study and its data tables; a query returns all tables in the study. PANGAEA, by contrast, creates an individual dataset for each table (a one-to-one relationship), with collections serving as the grouping mechanism.

Also notice the string returned by `PyleoTUPS` under the `q` key. As mentioned in the preamble, PANGAEA searches are string-based, with certain keys (such as author) that can be passed to the search. The `q` value is the actual query string that `PyleoTUPS` constructed from your search parameters.

Let's have a look at multiple authors search:

In [11]:
ds = pt.PangaeaDataset()
res = ds.search_studies(investigators = ["Khider, D.", "Richey, JN"])
display(res.head())

[2026-04-30 10:34:54,399][INFO] - Limit set to 100

{'q': 'author:Khider, D. author:Richey, JN', 'bbox': None, 'limit': 100, 'offset': 0}

[2026-04-30 10:37:22,541][INFO] - Retrived 100 studies
[2026-04-30 10:37:22,551][WARNING] - The search contains dataset(s) [897517, 760802, 818286, 830589, 760896, 761045, 729394, 760942, 783929, 761115, 760882, 761025, 729401, 760903, 729434, 729668, 761020, 762793, 784082, 729328, 760764, 760933, 760812, 760820, 943589, 784131, 762766, 729268, 784120, 762803, 760923, 989348, 935987, 921315, 949077, 761094, 773313, 859372] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,897517,Globigerinoides ruber sediment trap data in th...,NaN,NaN,NaN,NaN,We present results here from a high-resolution...,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[],[],"[897509, 897512, 897513, 897514, 897515, 897516]"
1,897512,Globigerinoides ruber flux analysis from a lon...,NaN,NaN,NaN,NaN,NaN,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
2,897516,CTD data from a long-running sediment trap tim...,NaN,NaN,NaN,NaN,NaN,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
3,897514,Magnesium/Calcium ratio of Globigerinoides rub...,NaN,NaN,NaN,NaN,NaN,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
4,897509,Carbonate measurements from a long-running sed...,NaN,NaN,NaN,NaN,NaN,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None

We have hit the limit! Like we have seen with NOAA queries, `PyleoTUPS` is conducting an `OR` search by defaults. So it is looking for all the studies authored by either one of the investigators. 

To do an `AND` query:

## Geographical query

Let's perform the same query as we did previously on NOAA NCEI for all the datasets within 5°S-5°N and 109-125°E, roughly corresponding to the Indo-Pacific Warm Pool. For speed, we will limit the search to the first 50 datasets.

<div style="border-left: 4px solid #1f77b4; background: #f0f8ff; padding: 0.5em 1em; border-radius: 4px;">
  <strong>Note:</strong> Like NOAA NCEI, PANGAEA offers `limit` and `skip` parameters for larger queries.
</div>

In [14]:
res = ds.search_studies(max_lat=5, min_lat=-5, max_lon=109,
                       min_lon=125, limit = 50)

[2026-04-30 10:40:31,815][INFO] - Limit set to 50

{'q': '', 'bbox': (125, -5, 109, 5), 'limit': 50, 'offset': 0}

[2026-04-30 10:40:32,598][INFO] - Retrived 149 studies
[2026-04-30 10:40:32,613][WARNING] - The search contains dataset(s) [897517, 760802, 818286, 830589, 760896, 761045, 729394, 760942, 783929, 761115, 760882, 761025, 729401, 760903, 729434, 729668, 761020, 762793, 784082, 729328, 760764, 760933, 760812, 760820, 943589, 784131, 762766, 729268, 784120, 762803, 760923, 989348, 935987, 921315, 949077, 761094, 773313, 859372, 974323, 884026, 945184, 907164, 893362, 908012, 931789, 832852, 889777, 807060, 948261, 882207, 906264, 893251, 904320, 863918, 783095, 858234, 962319, 842136, 986565, 887797, 875162, 959573, 950248, 882093, 820222, 726830, 871490, 910698, 885760, 974693, 972097, 788547, 890541, 871600, 875106, 871703, 962646, 736003, 858610, 938223, 701361, 772717, 863914, 859532, 875299] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

In [15]:
display(res.head())

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,897517,Globigerinoides ruber sediment trap data in th...,NaN,NaN,NaN,NaN,We present results here from a high-resolution...,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[],[],"[897509, 897512, 897513, 897514, 897515, 897516]"
1,897512,Globigerinoides ruber flux analysis from a lon...,NaN,NaN,NaN,NaN,NaN,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
2,897516,CTD data from a long-running sediment trap tim...,NaN,NaN,NaN,NaN,NaN,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
3,897514,Magnesium/Calcium ratio of Globigerinoides rub...,NaN,NaN,NaN,NaN,NaN,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
4,897509,Carbonate measurements from a long-running sed...,NaN,NaN,NaN,NaN,NaN,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None

## Variable queries

Let's search using variable names. In PANGAEA, this concept is closely related to [Parameter](https://wiki.pangaea.de/wiki/Parameter) and this is the reason why we mapped this concept to our key `variable_name`. But Parameter also include units. For a complete list of available parameters in PANGAEA, see [this wiki page](https://wiki.pangaea.de/wiki/Parameter).

In [16]:
ds = pt.PangaeaDataset()
res = ds.search_studies(variable_name = 'Temperature', limit=50)

[2026-04-30 11:30:15,414][INFO] - Limit set to 50

{'q': 'parameter:Temperature', 'bbox': None, 'limit': 50, 'offset': 0}

[2026-04-30 11:31:59,860][INFO] - Retrived 50 studies

In [17]:
display(res.head())

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,973997,Ready-to-use version of the Eurasian Modern Po...,NaN,NaN,NaN,NaN,Ready-to-use version of the Eurasian Modern Po...,"[Eurasian Modern Pollen Database version 2, Pa...","Zumaque, Jena, de Vernal, Anne, Fréchette, Bia...","Zumaque, Jena; de Vernal, Anne; Fréchette, Bia...","[AlbaSanchez_EMPD, Antipina_EMPD, Atanassova_E...",[],None
1,859039,(Table 2) Paleoclimate reconstruction for paly...,NaN,NaN,NaN,NaN,Palynofloras of the Kocaçay and Cumaovasi basi...,[],"Kayseri Özer, Mine Sezgül, Sözbilir, Hasan, Ak...","Kayseri Özer, Mine Sezgül; Sözbilir, Hasan; Ak...","[Buyuk_Menderes_Graben, Cumaovasi_basin, Kocac...",[{'name': 'Neogene Climate Evolution in Eurasi...,None
2,872166,Holocene SST reconstructions from the southern...,10150000.0,422000.0,-10148050.0,-420050.0,This paper documents the last 10 ka evolution ...,[],"Mary, Yannick, Eynaud, Frédérique, Colin, Chri...","Mary, Yannick; Eynaud, Frédérique; Colin, Chri...",[PP10-07],[],None
3,937660,The average monthly and annual air temperature...,NaN,NaN,NaN,NaN,The average monthly and annual air temperature...,"[air temperature, Batagay, Batagay Yedoma, hum...","Vasil'chuk, Yurij K, Vasil'chuk, Jessica Yurev...","Vasil'chuk, Yurij K; Vasil'chuk, Jessica Yurev...","[Batagay_1949, Batagay_1950, Batagay_1951, Bat...",[],None
4,956199,UWBRAD 500-2000 MHz brightness temperature mea...,NaN,NaN,NaN,NaN,The dataset contains 500-2000 MHz brightness t...,"[Antarctica, Fast ice, firn, Glacier, Ice shel...","Andrews, Mark, Brogioni, Marco, Johnson, Joel","Andrews, Mark; Brogioni, Marco; Johnson, Joel ...",[ISSIUMAX],[],None

As you can see on the sample above, many studies on PANGAEA will not be paleoclimate related. When doing a variable search, it is strongly advised to narrow the topics if possible:

In [20]:
ds = pt.PangaeaDataset()
res = ds.search_studies(variable_name = 'Temperature', topic = 'Paleontology', limit=50)

[2026-04-30 11:36:16,466][INFO] - Limit set to 50

{'q': 'topic:Paleontology parameter:Temperature', 'bbox': None, 'limit': 50, 'offset': 0}

[2026-04-30 11:37:42,968][INFO] - Retrived 50 studies

In [21]:
display(res.head())

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,988979,Paleoenvironmental reconstructions from sedime...,2847.0,62.0,-897.0,1888.0,The data set contains paleoenvironmental recon...,"[Benthic foraminifera, Diatoms, Dinoflagellate...","Klyuvitkina, Tatiana S, Novichkova, Ekaterina ...","Klyuvitkina, Tatiana S; Novichkova, Ekaterina ...",[AMK75-6150],[],None
1,691315,Calculated surface water paleotemperatures for...,NaN,NaN,NaN,NaN,The oxygen isotope record of the planktonic fo...,[],"Kammer, Thomas W","Kammer, Thomas W (1979): Calculated surface wa...",[18-173],"[{'name': 'Deep Sea Drilling Project', 'url': ...",None
2,54989,(Table 1) Transfer function results and sea su...,NaN,NaN,NaN,NaN,NaN,[],"Niebler, Hans-Stefan","Niebler, Hans-Stefan (1998): (Table 1) Transfe...","[A260210A, GeoB1203-2, GeoB1204-3, GeoB1218-1,...",[{'name': 'Paleoenvironmental Reconstructions ...,None
3,831475,(Table 1) Biogeographic distribution of living...,NaN,NaN,NaN,NaN,This paper adds to a series of studies address...,[],"Saavedra-Pellitero, Mariem, Baumann, Karl-Hein...","Saavedra-Pellitero, Mariem; Baumann, Karl-Hein...","[PS75/034-3, PS75/040-2, PS75/044-1, PS75/052-...",[{'name': 'Center for Marine Environmental Sci...,None
4,683526,Late Pliocene sea-surface temperature record o...,4095000.0,1931000.0,-4093050.0,-1929050.0,Application of quantitative micropaleontologic...,[],"Dowsett, Harry J, Loubere, Paul","Dowsett, Harry J; Loubere, Paul (1992): Late P...",[80-548],"[{'name': 'Deep Sea Drilling Project', 'url': ...",None

## Text search

It is possible to further refine queries by using the open `search_text` parameter. For instance, let's try to look for Holocene records:

In [22]:
ds = pt.PangaeaDataset()
res = ds.search_studies(variable_name = 'Temperature', topic = 'Paleontology', search_text = 'Holocene', limit=50)
display(res.head())

[2026-04-30 11:40:51,677][INFO] - Limit set to 50

{'q': 'topic:Paleontology Holocene parameter:Temperature', 'bbox': None, 'limit': 50, 'offset': 0}

/Users/deborahkhider/anaconda3/envs/tups/lib/python3.12/site-packages/pangaeapy/pandataset.py:1052: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.data["Event"] = self.events[0].label
/Users/deborahkhider/anaconda3/envs/tups/lib/python3.12/site-packages/pangaeapy/pandataset.py:1059: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.data["Latitude"] = np.nan
/Users/deborahkhider/anaconda3/envs/tups/lib/python3.12/site-packages/pangaeapy/pandataset.py:1063: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.data["Longitude"] = np.nan
/Users/deborahkhider/anaconda3/envs/tups/lib/python3.12/site-packages/pangaeapy/pandataset.py:1067: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.data["Elevation"] = np.nan
/Users/deborahkhider/anaconda3/envs/tups/lib/python3.12/site-packages/pangaeapy/pandataset.py:1071: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.data["Date/Time"] = "NaN"
[2026-04-30 11:42:44,432][INFO] - Retrived 50 studies

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,844989,(Appendix) Gephyrocapsa coccolith abundance an...,NaN,NaN,NaN,NaN,A global sea surface temperature calibration b...,[],"Bollmann, Jörg, Henderiks, Jorijntje, Brabec, ...","Bollmann, Jörg; Henderiks, Jorijntje; Brabec, ...","[182-1127B, A152-84, BATS_SedTrap_10013, Danut...",[],None
1,438366,Age and alkenone-derived Holocene sea-surface ...,11370.0,1990.0,-9420.0,-40.0,NaN,[],"Giunta, S, Emeis, Kay-Christian","Giunta, S; Emeis, Kay-Christian (2006): Age an...",[AD91-17],[],None
2,905507,Holocene sea-surface reconstructions in the Ca...,10831.0,914.0,-8881.0,1036.0,NaN,"[Arctic, Climate change, Holocene, Micropaleon...","Ledu, David","Ledu, David (2019): Holocene sea-surface recon...",[2005-804-004],[],None
3,905510,Holocene sea-surface reconstructions in the Ca...,11113.0,2034.0,-9163.0,-84.0,NaN,"[Arctic, Climate change, Holocene, Micropaleon...","Ledu, David","Ledu, David (2019): Holocene sea-surface recon...",[2004-804-009],[],None
4,905508,Holocene sea-surface reconstructions in the Ca...,7730.0,1023.0,-5780.0,927.0,NaN,"[Arctic, Micropaleontology, Paleooceanography]","Ledu, David","Ledu, David (2019): Holocene sea-surface recon...",[2005-804-006],[],None

As long as the word "Holocene" appears anywhere in the metadata (dataset name, study name, or description), the search will return those datasets. However, this does not mean that other datasets covering the Holocene are absent from PANGAEA — a study described as spanning "the past 15,000 years" would not be matched. Because age bounds are not part of PANGAEA's standard metadata, time-based searches are severely limited.

## Dealing with Collections

Collections link Datasets together. They can be very powerful, but also difficult to deal with when interested in the data only. 

Let's do a search query for the data is supplement to [van der Bilt et al. (2016)](https://doi.org/10.1016/j.quascirev.2016.10.006). To do so we will be using:
* `investigators` parameter in `search_studies`
* `search_text` to narrow down the publication year using the PANGAEA field `citation:year:` as seen [here](https://wiki.pangaea.de/wiki/PANGAEA_search):

In [2]:
ds = pt.PangaeaDataset()
res = ds.search_studies(investigators = 'van der Bilt', search_text = 'citation:year:2016', limit=50)

[2026-05-01 08:20:14,049][INFO] - Limit set to 50

{'q': 'citation:year:2016 author:van der Bilt', 'bbox': None, 'limit': 50, 'offset': 0}

[2026-05-01 08:20:20,433][INFO] - Retrived 3 studies
[2026-05-01 08:20:20,434][WARNING] - The search contains dataset(s) [868938] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

As you can see, `PyleoTUPS` created the string query `q` from both the exposed parameter `investigators` and the PANGAEA field `citation:year:`.

Let's have a look at the returned datasets:

In [3]:
display(res)

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,868938,Holocene-length alkenone-based summer temperar...,NaN,NaN,NaN,NaN,Situated at the crossroads of global oceanic a...,[],"van der Bilt, Willem G M, D'Andrea, William J,...","van der Bilt, Willem G M; D'Andrea, William J;...",[],[],"[868935, 868936]"
1,868935,Holocene-length alkenone-based summer temperat...,12353.0,1144.0,-10403.0,806.0,NaN,[],"van der Bilt, Willem G M, D'Andrea, William J,...","van der Bilt, Willem G M; D'Andrea, William J;...",[AMP112],[],None
2,868936,Holocene-length alkenone-based summer temperat...,11117.0,533.0,-9167.0,1417.0,NaN,[],"van der Bilt, Willem G M, D'Andrea, William J,...","van der Bilt, Willem G M; D'Andrea, William J;...",[HAP0212],[],None

As noted earlier, the first dataset is actually a collection. If you scroll to the last column, you'll see a list of its collection members. One way to filter out collections is to remove all entries where collectionMembers is not NaN, then recreate a `PangaeaDataset` object:

In [14]:
ids = []

for idx,row in res.iterrows():
    if row.at['CollectionMembers'] is not None:
        ids.extend(row['CollectionMembers'])

ds2 = pt.PangaeaDataset()
res2 = ds2.search_studies(study_ids = ids)

[2026-05-01 09:43:38,225][INFO] - Registering Study 868935 via direct lookup.
[2026-05-01 09:43:39,985][INFO] - Registering Study 868936 via direct lookup.
[2026-05-01 09:43:41,574][INFO] - Retrived 2 studies

## Summary

In this tutorial, you learned how to use the search_studies function with the PANGAEA database. A few things to keep in mind:

1. PANGAEA is more general-purpose than NOAA NCEI for paleo. While this means instrumental datasets may also appear in results, search parameters common in paleoclimate queries (e.g., age) are unavailable on PANGAEA. Additionally, PANGAEA lacks the rich controlled vocabulary of NOAA NCEI, which can make broad searches more difficult.
2. Some datasets require login credentials to access.
3. Collections are returned alongside individual datasets, so care is needed when linking them back together.